<?php
// SPDX-License-Identifier: AGPL-3.0-or-later
/** @var \Icinga\Web\View $this */
/** @var \Icinga\Web\Widget\Tabs $tabs */
/** @var stdClass $politPrisoner */
/** @var string[] $excelLists */
/** @var stdClass[] $infoLinks */
/** @var stdClass[] $fields */
?>
<div class="controls"><?= $tabs ?></div>
<div class="content">
    <table class="name-value-list common-table">
        <tbody>
        <tr>
            <td><?= $this->escape($this->translate('Name')) ?></td>
            <td<?= ($politPrisoner->vanished ? ' class="vanished"' : '') ?>><?=
                $this->escape($politPrisoner->name)
                ?></td>
        </tr>
        <tr>
            <td><?= $this->escape($this->translate('Born')) ?></td>
            <td><?= $politPrisoner->born === null
                    ? '?' : $this->escape(strftime('%x', (new DateTime($politPrisoner->born))->getTimestamp())) ?></td>
        </tr>
        <tr>
            <td><?= $this->escape($this->translate('List')) ?></td>
            <?php if (isset($excelLists[$politPrisoner->source])): ?>
                <td><?= $this->escape($excelLists[$politPrisoner->source]) ?></td>
            <?php else: ?>
                <td class="vanished"><?= $this->escape($politPrisoner->source) ?></td>
            <?php endif; ?>
        </tr>
        <?php if (!empty($infoLinks)): ?>
            <tr>
                <td><?= $this->escape($this->translate('Details')) ?></td>
                <td>
                    <?php if (count($infoLinks) > 1): ?>
                        <ul>
                            <?php foreach ($infoLinks as $infoLink): ?>
                                <li><a target="_blank" href="<?= $this->escape($infoLink->url) ?>"><?=
                                        $this->escape($infoLink->display_name)
                                        ?></a></li>
                            <?php endforeach; ?>
                        </ul>
                    <?php else: ?>
                        <?php foreach ($infoLinks as $infoLink): ?>
                            <a class="action-link" target="_blank" href="<?= $this->escape($infoLink->url) ?>"><?=
                                $this->escape($infoLink->display_name)
                                ?></a>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endif; ?>
        <?php foreach ($fields as $field): ?>
            <tr>
                <td<?= ($field->vanished ? ' class="vanished"' : '') ?>><?= $this->escape($field->name) ?></td>
                <td><?= $this->escape($field->value) ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
