<?php
// SPDX-License-Identifier: AGPL-3.0-or-later
/** @var \Icinga\Web\View $this */
/** @var \Icinga\Web\Widget\Tabs $tabs */
/** @var \Icinga\Repository\RepositoryQuery $items */
?>
<div class="controls"><?= $tabs ?></div>
<div class="content">
    <p><?= $this->qlink(
            $this->translate('New'),
            'manufaktura_elfov/infolinks/create',
            null,
            [
                'class' => 'button-link',
                'icon' => 'plus',
                'data-icinga-modal' => true,
                'data-no-icinga-ajax' => true
            ]
        ) ?></p>
    <table data-base-target="_next" class="common-table">
        <tbody>
        <?php foreach ($items as $item): ?>
            <tr data-base-target="_self" data-icinga-modal data-no-icinga-ajax href="<?=
            $this->href('manufaktura_elfov/infolinks/edit', ['uuid' => $item->uuid])
            ?>">
                <td><?= $this->escape($item->display_name) ?></td>
                <td><?= $this->qlink(
                        null,
                        'manufaktura_elfov/infolinks/remove',
                        ['uuid' => $item->uuid],
                        [
                            'class' => 'button-link',
                            'icon' => 'trash',
                            'data-icinga-modal' => true,
                            'data-no-icinga-ajax' => true
                        ]
                    ) ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
